# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-30 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busphoto',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_photos', to='bus.Bus'),
        ),
    ]
