# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-02 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20181001_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ('title',), 'verbose_name': 'Автобус', 'verbose_name_plural': 'Автобусы'},
        ),
    ]
