# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-17 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_auto_20181002_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='title_en',
        ),
    ]
