# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-05 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180804_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='_meta_title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='gen_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='in_sitemap',
        ),
        migrations.RemoveField(
            model_name='service',
            name='keywords_string',
        ),
        migrations.RemoveField(
            model_name='service',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='short_content',
        ),
        migrations.RemoveField(
            model_name='service',
            name='short_content_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='short_content_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='short_url',
        ),
        migrations.RemoveField(
            model_name='service',
            name='site',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated',
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.TextField(max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_en',
            field=models.TextField(max_length=300, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_ru',
            field=models.TextField(max_length=300, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название услуги'),
        ),
    ]
