# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-02 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20180805_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('title',), 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
