# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-24 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20181124_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.TextField(blank=True, max_length=300, verbose_name='Описание'),
        ),
    ]
