# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-20 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20181124_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('order', 'title'), 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(null=True, verbose_name='Порядковый номер'),
        ),
    ]
