# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-29 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields
import mezzanine.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', mezzanine.core.fields.FileField(max_length=255, verbose_name='Изображение')),
                ('caption', models.CharField(max_length=150, verbose_name='Наименование')),
                ('caption_ru', models.CharField(max_length=150, null=True, verbose_name='Наименование')),
                ('caption_en', models.CharField(max_length=150, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
            bases=(models.Model, mezzanine.utils.models.AdminThumbMixin),
        ),
    ]
