# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-02 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('caption',), 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
