# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-20 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_document_caption_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('order', 'caption'), 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.IntegerField(null=True, verbose_name='Порядковый номер'),
        ),
    ]
