# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-04 10:30
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models
import mezzanine.core.fields
import mezzanine.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPagePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', mezzanine.core.fields.FileField(max_length=500, verbose_name='Изображение')),
                ('position', models.CharField(choices=[('MAIN', 'Главное изображение'), ('FAKE', 'Не используется')], default='FAKE', max_length=50, verbose_name='Где используется')),
                ('font_color', models.CharField(blank=True, help_text='Цвет текста в формате #rrggbb', max_length=7, null=True, validators=[common.validators.HexColorValidator()], verbose_name='Цвет текста')),
            ],
            options={
                'verbose_name': 'Картинка на главной',
                'verbose_name_plural': 'Картинки на главной',
            },
            bases=(mezzanine.utils.models.AdminThumbMixin, models.Model),
        ),
    ]
