# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-03 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Код')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, max_length=5000, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Тексты',
            },
        ),
    ]
