# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-02 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ('title',), 'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
    ]
