# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-20 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0004_auto_20181124_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ('order', 'title'), 'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
        migrations.AddField(
            model_name='benefit',
            name='order',
            field=models.IntegerField(null=True, verbose_name='Порядковый номер'),
        ),
    ]
