# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields
import mezzanine.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Автор отзыва')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Автор отзыва')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Автор отзыва')),
                ('is_company', models.BooleanField(default=False, verbose_name='Организация')),
                ('photo', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Логотип или фото')),
                ('content', models.TextField(max_length=500, verbose_name='Описание')),
                ('content_ru', models.TextField(max_length=500, null=True, verbose_name='Описание')),
                ('content_en', models.TextField(max_length=500, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-is_company', 'title'),
            },
            bases=(models.Model, mezzanine.utils.models.AdminThumbMixin),
        ),
    ]
